# -*- coding: utf-8 -*-
"""Spark ML Lib Introduction (For YouTube).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tDqxKNpSYGQf_gg-1DLwhLqjMdTcFuy1
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder\
        .master("local")\
        .appName("Colab")\
        .config('spark.ui.port', '4050')\
        .getOrCreate()

spark

df = spark.read.format("csv").load("housing.csv", header=True, inferSchema=True)

df.printSchema()

df.show(5)

from pyspark.sql.functions import monotonically_increasing_id

df = df.withColumn('id', monotonically_increasing_id())

df = df[['id'] + df.columns[:-1]]

df.show(3)

df.count()

df.select('total_rooms').agg({'total_rooms': 'avg'}).show()

from pyspark.sql.functions import mean

df.select(*[mean(c) for c in df.columns]).show()

df.groupby('ocean_proximity').agg({col: 'avg' for col in df.columns[3:-1]}).show()

from pyspark.sql.types import FloatType
from pyspark.sql.functions import udf
